default: 
    image: node:latest

build-job:
    stage: build
    script:
        - echo "Build brunch"
        - yarn
        - yarn build

deploy-job:
    stage: deploy
    script:
        - echo "Deploy brunch"



