stages:
    - build
    - test
    - deploy

default: 
    image: node:latest

build-job:
    stage: build
    script:
        - echo "Build brunch"
        - yarn
        - yarn build

test-job:
    stage: test
    script:
        - echo "test"

deploy-job:
    stage: deploy
    script:
        - echo "Deploy brunch"



