default: 
    image: node:latest

build-job:
    stage: build
    script:
        - echo "Build brunch"
        - docker-compose build
deploy-job:
    stage: Deploy
    script:
        - echo "Deploy brunch"
        - docker-compose up -d

