version: "3.0"

services: 
  web:
    image: 10.250.8.1:5050/root/hello-brunch:latest
    ports:
      - "80:80"
    logging:
      driver: fluentd
      options:
        fluentd-address: "10.250.8.1:24224"
