version: "3.0"

services: 
  web:
    image: hello-brunch
    ports:
      - "80:80"
    logging:
      driver: loki
      options:
        loki-url: "http://10.250.8.1:3100/loki/api/v1/push"
        loki-retries: 5 
        loki-batch-size: 400
