version: "3.0"

services: 
  web:
    image: 10.250.8.1:5050/root/hello-brunch:latest
    ports:
      - "80:80"
    logging:
      driver: loki
      options:
        loki-url: "http://10.250.8.1:3100/loki/api/v1/push"
