version: "3.0"

services: 
  web:
    image: image: 10.250.8.1:5050/root/hello-brunch:latest
    ports:
      - "80:80"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://10.250.8.1:5000"
        syslog-format: "rfc5424"
        tag: "hello-brunch"
